// *************************************
// **      DO NOT EDIT THIS FILE      **
// *************************************
import 'dart:typed_data';
import 'package:json_annotation/json_annotation.dart';
import 'dart:convert';

class Uint8Converter implements JsonConverter<Uint8List, Object> {
  const Uint8Converter();

  @override
  Uint8List fromJson(Object json) {
    if (json == null) {
      return null;
    }

    if (json is Map) {
      List<int> list = base64.decode(json['\$value']);
      Uint8List bytes = Uint8List.fromList(list);
      return bytes;
    }

    if (json is String) {
      List<int> list = base64.decode(json);
      Uint8List bytes = Uint8List.fromList(list);
      return bytes;
    }

    throw new Exception("Invalid Uint8List conversion!!");
  }

  Uint8List fromJsonDynamic(Object json) {
    return fromJson(json);
  }

  @override
  Object toJson(Uint8List object) {
    return object ?? base64.encode(object);
  }

  Object toJsonDynamic(Uint8List object) {
    return toJson(object);
  }
}

class DateTimeConverter implements JsonConverter<DateTime, Object> {
  const DateTimeConverter();

  @override
  DateTime fromJson(Object json) {
    if (json == null) {
      return null;
    }

    if (json is String) {
      return DateTime.parse(json);
    }

    throw new Exception("Invalid DateTime conversion!!");
  }

  DateTime fromJsonDynamic(Object json) {
    return fromJson(json);
  }

  @override
  Object toJson(DateTime object) {
    return object?.toIso8601String() ?? object;
  }

  Object toJsonDynamic(DateTime object) {
    return toJson(object);
  }
}
