//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlutnetUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlutnetUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;h2ava&quot;&gt;
        ///Please follow the instructions to fix them, then press &lt;b&gt;Check again&lt;/b&gt; to re-run the diagnostic process.&lt;br&gt;&lt;br&gt;
        ///If you encounter some troubles in fixing the errors, let Flutnet help you in the configuration: press &lt;b&gt;Assisted setup&lt;/b&gt; and follow the step-by-step procedure.&lt;br&gt;&lt;br&gt;
        ///If Android SDK is missing and you do not intend to create Xamarin.Android projects, just ignore the error and press &lt;b&gt;Ignore and continue&lt;/b&gt; to jump to the next step.
        ///&lt;/div&gt;.
        /// </summary>
        internal static string Setup_Check_FlutterErrors_Message {
            get {
                return ResourceManager.GetString("Setup_Check_FlutterErrors_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;h2ava&quot;&gt;
        ///Unable to locate Flutter.&lt;br&gt;&lt;br&gt;
        ///Please download the latest supported SDK from &lt;a href=&quot;@FLUTTER_SDK_DOWNLOAD_URL@&quot;&gt;here&lt;/a&gt; and follow the &lt;a href=&quot;@FLUTTER_INSTALL_PAGE@&quot;&gt;install instructions&lt;/a&gt; on Flutter website. If you don&apos;t want to install Android Studio, you can read through &lt;a href=&quot;@FLUTNET_INSTALL_PAGE@&quot;&gt;Flutnet documentation&lt;/a&gt; to set all the required environment variables.&lt;br&gt;&lt;br&gt;
        ///If you already downloaded Flutter, you might not have updated your path: please read the &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Setup_Check_FlutterNotFound_Message {
            get {
                return ResourceManager.GetString("Setup_Check_FlutterNotFound_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;h2ava&quot;&gt;
        ///Congratulations!&lt;br&gt;&lt;br&gt;
        ///Everything is set up properly, you should now be able to create and run Flutnet projects.&lt;br&gt;&lt;br&gt;
        ///Flutter version: @FLUTTER_VERSION_CURRENT@
        ///&lt;/div&gt;.
        /// </summary>
        internal static string Setup_Finish_Congratulations_v1_Message {
            get {
                return ResourceManager.GetString("Setup_Finish_Congratulations_v1_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;h2ava&quot;&gt;
        ///Congratulations!&lt;br&gt;&lt;br&gt;
        ///Your system has been set up successfully. Please &lt;b&gt;restart the application&lt;/b&gt; for the changes to take effect.
        ///&lt;/div&gt;.
        /// </summary>
        internal static string Setup_Finish_Congratulations_v2_Message {
            get {
                return ResourceManager.GetString("Setup_Finish_Congratulations_v2_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;h2ava&quot;&gt;
        ///You&apos;re using a Flutter release that isn&apos;t officially compatible with Flutnet: the resulting projects may not work or may exhibit unexpected behaviors.&lt;br&gt;&lt;br&gt;
        ///We recommend that you update Flutter to the latest supported Flutter SDK - @FLUTTER_VERSION_TARGET@. You can find it &lt;a href=&quot;@FLUTTER_SDK_DOWNLOAD_URL@&quot;&gt;here&lt;/a&gt;.
        ///&lt;/div&gt;.
        /// </summary>
        internal static string Setup_Finish_LimitedSupport_v1_Message {
            get {
                return ResourceManager.GetString("Setup_Finish_LimitedSupport_v1_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;h2ava&quot;&gt;
        ///You&apos;re using a Flutter release that isn&apos;t officially compatible with Flutnet: the resulting projects may not work or may exhibit unexpected behaviors.&lt;br&gt;&lt;br&gt;
        ///We recommend that you download and configure the latest supported Flutter SDK - @FLUTTER_VERSION_TARGET@. You can find it &lt;a href=&quot;@FLUTTER_SDK_DOWNLOAD_URL@&quot;&gt;here&lt;/a&gt;.
        ///&lt;/div&gt;.
        /// </summary>
        internal static string Setup_Finish_LimitedSupport_v2_Message {
            get {
                return ResourceManager.GetString("Setup_Finish_LimitedSupport_v2_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;h2ava&quot;&gt;
        ///Unfortunately you&apos;re using a Flutter release that isn&apos;t compatible with Flutnet.&lt;br&gt;&lt;br&gt;
        ///Please download the latest supported SDK - @FLUTTER_VERSION_TARGET@ - from official Flutter website. You can find it &lt;a href=&quot;@FLUTTER_SDK_DOWNLOAD_URL@&quot;&gt;here&lt;/a&gt;.
        ///&lt;/div&gt;.
        /// </summary>
        internal static string Setup_Finish_NoCompatibility_Message {
            get {
                return ResourceManager.GetString("Setup_Finish_NoCompatibility_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;h2ava&quot;&gt;
        ///An unexpected error occured.&lt;br&gt;&lt;br&gt;
        ///Please re-launch this wizard and try again. If the problem persists, do not hesitate to &lt;a href=&quot;mailto:support@flutnet.com&quot;&gt;contact us&lt;/a&gt;.
        ///&lt;/div&gt;.
        /// </summary>
        internal static string Setup_Finish_UnexpectedError_Message {
            get {
                return ResourceManager.GetString("Setup_Finish_UnexpectedError_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.h2ava {
        ///    font-size: 22px;
        ///    text-align: justify;
        ///    text-justify: inter-word;
        ///}
        ///.
        /// </summary>
        internal static string Setup_Styles {
            get {
                return ResourceManager.GetString("Setup_Styles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;h2ava&quot;&gt;Thanks for using Flutnet!
        ///&lt;br&gt;&lt;br&gt;
        ///This wizard will check your system to ensure that everything is setup correctly and will assist you in configuring all the required components.
        ///&lt;br&gt;&lt;br&gt;
        ///If you&apos;ve already succeeded in creating a project, but you&apos;re experiencing some troubles in getting started, please consult our &lt;a href=&quot;https://www.flutnet.com/Documentation/Getting-Started/Build-and-Run-Step-by-Step&quot;&gt;online documentation&lt;/a&gt;&lt;/div&gt;.
        /// </summary>
        internal static string Setup_Welcome_Message {
            get {
                return ResourceManager.GetString("Setup_Welcome_Message", resourceCulture);
            }
        }
    }
}
